    	DO READ OUT #1
(2)	PLEASE DO (4) NEXT
	DO READ OUT #9
	DO REINSTATE (18)
	DO (110) NEXT
(4)	PLEASE DO (7) NEXT
	DO REINSTATE (9)
	PLEASE DO READ OUT #3
(7)	DO (100) NEXT
	DO YOU REALISE THAT THIS SHOULD BE UNREACHABLE?
(9)	DON'T COME FROM (100)
(110)	DO (21) NEXT
	DO READ OUT #6
	DO (120) NEXT
	DO FORGET THINGS CORRECTLY
(120)	DO READ OUT #7
	DO AVOID THIS LINE TOO
(18)	DON'T COME FROM (9)
	DO READ OUT #12
	PLEASE DO .1 <- #13
	PLEASE DO (130) NEXT
	DO READ OUT .1
	PLEASE DO (140) NEXT
	PLEASE DO .17 <- #15
	DO T .17
	DO READ OUT .17
	DO GIVE UP
(21)	PLEASE DO READ OUT #4 ONCE
	DON'T READ OUT #10 ONCE
	PLEASE DO RESUME #1
